apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-city-weahter-app
  namespace: argocd 
spec:
  destination: 
    namespace: gitops-kubernetes
    server: https://kubernetes.default.svc 
  project: default 
  source:
    repoURL: https://github.com/DeZin7/gitops-k8s-deployments-book-weather-app
    path: deployment
    targetRevision: main